version: '3.8'

services:
  condor-manager:
    image: htcondor/cm:el7
    container_name: condor-manager
    hostname: condor-manager
    environment:
      - CONDOR_HOST=condor-manager
      - USE_SHARED_PORT=yes
    networks:
      - htcondor-net
    ports:
      - "9618:9618"

  condor-exec-1:
    image: htcondor/execute:el7
    container_name: condor-exec-1
    hostname: condor-exec-1
    environment:
      - CONDOR_HOST=condor-manager
    depends_on:
      - condor-manager
    networks:
      - htcondor-net

  condor-exec-2:
    image: htcondor/execute:el7
    container_name: condor-exec-2
    hostname: condor-exec-2
    environment:
      - CONDOR_HOST=condor-manager
    depends_on:
      - condor-manager
    networks:
      - htcondor-net

  condor-submit:
    image: htcondor/submit:el7
    container_name: condor-submit
    hostname: condor-submit
    environment:
      - CONDOR_HOST=condor-manager
    depends_on:
      - condor-manager
    networks:
      - htcondor-net
    volumes:
      - ./jobs:/jobs

networks:
  htcondor-net:
    driver: bridge
